[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ErrorBoundedCompressionPipeline"
version = "0.1"

[tool.setuptools.packages.find]
include = ["error_bounded_compression_pipeline"]
